#!/usr/bin/env python3
"""The 2001 .hex oracle.

tb/base.7z ships, for each of the ten projects, both www8051.rom and www8051.hex.
The .rom files have since been regenerated by this port; the .hex files never
were, so projekt/*/www8051.hex is the one artefact in this repository that no run
of the current toolchain has ever touched.  It is what the 2001 web51 port of
binutils 2.11.2 emitted.

That output is not byte-correct.  The 2001 linker read and wrote every 16-bit
relocated field little-endian, and left every 8-bit internal-RAM / bit operand at
zero, so a plain cmp against it is worthless.  What it still pins exactly is the
code layout: the length of every instruction, the low byte of every code address,
and the size of .text.  This script compares against it structurally - it
classifies every differing byte into one of the known 2001 relocation defects and
fails when a byte fits none of them, or when the size delta or ANY of the six
byte-class counts moves away from what is recorded here - addr16, acall11,
word16, pcode13, zero8 and residual alike, not the residual one alone.

Classes, every one of them a 2001-side defect unless said otherwise:

  addr16    LJMP / LCALL / MOV DPTR,#addr16.  The field sits at offset+1 of the
            instruction and the object's placeholder holds two zero bytes.  Read
            and written little-endian, the low byte lands where the ISA wants the
            high byte and the high byte lands in the second placeholder zero,
            which is then never written back.  2001 = (lo, 0x00) where the ISA
            wants (hi, lo): LJMP 0x02e8 comes out `02 e8 00`, i.e. LJMP 0xe800.

  acall11   ACALL / AJMP.  Eleven bits, three of which live in the opcode byte
            (page << 5 | 0x11 or 0x01).  Same little-endian read/write pair, so
            the opcode bits are read out of the wrong byte and lost:
            2001 = (lo, hi & 0xE0) where the ISA wants (hi, lo).

  word16    A 16-bit datum - .word, and the pcode fields whose flag bits are
            zero anyway.  Bytes exchanged, nothing lost: 2001 = (lo, hi).

  pcode13   R_I51_13_PCODE, a 13-bit address with three flag bits above it that
            the relocation has to carry over from the object.  Read
            little-endian, the flags come out of the low byte and are masked
            away: 2001 = (lo, hi & 0x1F).  lib/pcode.asm reads those bits back
            with `JNB B2B(token,7)`..`,5` - the indirect flags for par1..par3.

  zero8     An 8-bit internal-RAM address, SFR or bit address that 2001 left at
            0x00.  `MOV SP,#stack` comes out `75 81 00` in all ten ROMs.

  residual  Everything else.  What is left is the one real difference between the
            two toolchains: an internal-RAM address a multiple of 8 higher in
            ours, because ref.7z's i51.patch.112p patches ld/ldlang.c to switch
            common alignment off for this target and mcs51/*.patch carries no
            Counted, budgeted, and listed byte by byte under --verbose.

Two projects cannot be laid out the way the 2001 ROM is, for reasons that have
nothing to do with the toolchain; both are recorded as explained size deltas and
their bytes are not classified.

Usage:
    python3 tb/hexoracle.py --tree work/oracle --oracle work/oracle-hex

--tree holds projekt/<p>/www8051.rom as produced by a run; --oracle holds
projekt/<p>/www8051.hex straight out of base.7z.  They have to be separate
directories because a project build overwrites www8051.hex with its own.
"""

import argparse
import os
import sys

PROJECTS = ["diag", "ds1620", "ds1822", "lcd", "led1", "led2", "led3",
            "serial", "welcome", "wjava"]

# Every column the table prints is pinned here, and every one of them is
# gated.  The script used to compute addr16/acall11/word16/pcode13/zero8 and
# then print them without comparing them against anything, so a fault that
# moves bytes from one class into another - a 16-bit relocation written
# little-endian moves them out of `addr16' and into `zero8' - left the verdict
# at "all 10 projects agree" while `make check' went red on all ten projects.
#
# oracle   : size of the 2001 ROM decoded from www8051.hex.  A change here
#            means the oracle itself was touched, which must never happen.
# delta    : produced size minus oracle size.  Zero for the eight projects
#            that share the 2001 layout; nonzero only where `reason'
#            explains it.
# counts   : the classification of every differing byte, all six buckets,
#            exactly as a clean run produces them.  None where a nonzero
#            delta makes a byte-for-byte walk meaningless, and then the
#            buckets are not computed at all.
#
# These numbers come from a clean run of `make -C tb oracle'.  They are not to
# be refreshed to whatever the tree currently prints: each is a joint property
# of the frozen 2001 image on one side and of a correct port on the other, so
# a moved count is a finding, not a stale expectation.


def _c(addr16, acall11, word16, pcode13, zero8, residual):
    return {"addr16": addr16, "acall11": acall11, "word16": word16,
            "pcode13": pcode13, "zero8": zero8, "residual": residual}


# The buckets, in the order the table prints them.  `residual' is one of them.
CLASSES = ["addr16", "acall11", "word16", "pcode13", "zero8", "residual"]

EXPECT = {
    #           oracle  delta   every differing byte, by class          reason
    "diag":    (1264,      3,  None,
                "2001 linked diag with ld's built-in i51 script, not www51.sc, "
                "so its orphan reset_network never reached .text and objcopy -j "
                ".text dropped it; base.7z's diag/Makefile adds --script.  diag "
                "is the one project that calls network_init from its own main, "
                "so the 2001 diag ROM works without those 3 bytes."),
    "ds1620":  (6284,      0,  _c(308, 1, 137, 25, 400, 25), None),
    "ds1822":  (6078,      0,  _c(357, 1, 141, 22, 427, 28), None),
    "lcd":     (5754,      0,  _c(321, 2, 137, 25, 422, 27), None),
    "led1":    (5173,      0,  _c(279, 1, 133, 25, 398, 25), None),
    "led2":    (5010,      0,  _c(281, 1, 135, 25, 422, 25), None),
    "led3":    (5200,      0,  _c(283, 1, 137, 25, 444, 25), None),
    "serial":  (9647,  -1519,  None,
                "2001 built index.html and setup.html with html2db.pl -cpurom "
                "and without -index 0: 1530 bytes of HTML in the ROM, 8 bytes of "
                "extra directory, ROM 9647 bytes - 1455 over the 8 KB `text` "
                "region www51.sc declares for the AT89S8252.  base.7z's "
                "serial/Makefile moved them to -cpueeprom, which is why ours "
                "fits and the 2001 image does not."),
    "welcome": (4812,      0,  _c(264, 1, 131, 25, 402, 25), None),
    "wjava":   (4812,      0,  _c(264, 1, 131, 25, 402, 25), None),
}


def read_ihex(path):
    """Decode an Intel HEX file into a flat image starting at address 0."""
    mem = {}
    with open(path, "r", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line.startswith(":"):
                continue
            rec = bytes.fromhex(line[1:])
            if sum(rec) & 0xFF:
                raise ValueError("%s: bad checksum in %r" % (path, line))
            count, addr, rtype = rec[0], (rec[1] << 8) | rec[2], rec[3]
            if rtype == 0:
                for i in range(count):
                    mem[addr + i] = rec[4 + i]
            elif rtype == 1:
                break
    if not mem:
        raise ValueError("%s: no data records" % path)
    return bytes(mem.get(a, 0xFF) for a in range(max(mem) + 1))


def classify(oracle, produced):
    """Walk both images once, bucketing every differing byte."""
    n = min(len(oracle), len(produced))
    counts = {"addr16": 0, "acall11": 0, "word16": 0, "pcode13": 0, "zero8": 0}
    residual = []
    i = 0
    while i < n:
        a, b = oracle[i], produced[i]
        if a == b:
            i += 1
            continue
        pair = i + 1 < n and oracle[i] == produced[i + 1]
        if pair and oracle[i + 1] == 0x00:
            counts["addr16"] += 1
            i += 2
        elif pair and oracle[i + 1] == produced[i]:
            counts["word16"] += 1
            i += 2
        elif pair and oracle[i + 1] == (produced[i] & 0xE0):
            counts["acall11"] += 1
            i += 2
        elif pair and oracle[i + 1] == (produced[i] & 0x1F):
            counts["pcode13"] += 1
            i += 2
        elif a == 0x00:
            counts["zero8"] += 1
            i += 1
        else:
            residual.append((i, a, b))
            i += 1
    return counts, residual


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--tree", required=True,
                    help="directory holding projekt/<p>/www8051.rom")
    ap.add_argument("--oracle",
                    help="directory holding projekt/<p>/www8051.hex "
                         "(default: --tree)")
    ap.add_argument("--projects", default=" ".join(PROJECTS))
    ap.add_argument("--verbose", action="store_true",
                    help="list every residual byte")
    args = ap.parse_args()

    oracle_root = args.oracle or args.tree
    projects = args.projects.split()
    failures = []
    notes = []

    header = ("project   2001   ours  delta  addr16 acall11  word16 pcode13"
              "   zero8  residual  verdict")
    print(header)
    print("-" * len(header))

    for p in projects:
        hexpath = os.path.join(oracle_root, "projekt", p, "www8051.hex")
        rompath = os.path.join(args.tree, "projekt", p, "www8051.rom")
        if not os.path.exists(hexpath):
            failures.append("%s: no 2001 oracle at %s" % (p, hexpath))
            print("%-8s  MISSING ORACLE" % p)
            continue
        if not os.path.exists(rompath):
            failures.append("%s: no produced ROM at %s" % (p, rompath))
            print("%-8s  NO ROM" % p)
            continue

        oracle = read_ihex(hexpath)
        produced = open(rompath, "rb").read()
        delta = len(produced) - len(oracle)
        want_oracle, want_delta, want_counts, reason = EXPECT[p]

        if len(oracle) != want_oracle:
            failures.append("%s: the 2001 oracle decodes to %d bytes, recorded "
                            "%d - base.7z's www8051.hex was modified"
                            % (p, len(oracle), want_oracle))

        verdict = "ok"
        counts = {k: 0 for k in CLASSES}
        residual = []

        if delta != want_delta:
            verdict = "SIZE %+d" % (delta - want_delta)
            failures.append("%s: produced %d bytes against the 2001 oracle's %d "
                            "(delta %+d, recorded %+d)"
                            % (p, len(produced), len(oracle), delta, want_delta))
        elif want_counts is None:
            verdict = "explained %+d" % delta
            notes.append("%s: %+d bytes, explained - %s" % (p, delta, reason))
        else:
            counts, residual = classify(oracle, produced)
            counts["residual"] = len(residual)
            # Every bucket is gated, not just the residual one.  A byte that
            # moves from one class to another is a change in what the port
            # emits even when the totals still add up.
            moved = ["%s %d (recorded %d)" % (k, counts[k], want_counts[k])
                     for k in CLASSES if counts[k] != want_counts[k]]
            if moved:
                first = [k for k in CLASSES if counts[k] != want_counts[k]][0]
                verdict = "%s %+d" % (first, counts[first] - want_counts[first])
                failures.append("%s: %s" % (p, ", ".join(moved)))

        print("%-8s %6d %6d %6d  %6d  %6d  %6d  %6d  %6d  %8d  %s"
              % (p, len(oracle), len(produced), delta, counts["addr16"],
                 counts["acall11"], counts["word16"], counts["pcode13"],
                 counts["zero8"], counts["residual"], verdict))

        if args.verbose:
            for off, a, b in residual:
                print("    residual @0x%04x  2001=%02x ours=%02x  (%+d)"
                      % (off, a, b, b - a))

    print()
    for n in notes:
        print("note: %s" % n)
    if notes:
        print()
    if failures:
        for f in failures:
            print("FAIL %s" % f)
        bad = len({f.split(":")[0] for f in failures})
        print("\n%d of %d projects deviate from the 2001 oracle"
              % (bad, len(projects)))
        return 1
    print("all %d projects agree with the 2001 oracle: recorded size delta, "
          "and every one of %s at its recorded count"
          % (len(projects), "/".join(CLASSES)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
